# Generated by Django 2.2.11 on 2020-04-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200420_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='locked_by_anonymous',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='locked_by_user',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='page',
        ),
        migrations.AddField(
            model_name='poem',
            name='lock_code',
            field=models.IntegerField(null=True),
        ),
    ]
