# Generated by Django 2.2.11 on 2020-04-22 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200422_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='lock_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poem_verses', to='app.Poem'),
        ),
    ]
