# Generated by Django 2.2.11 on 2020-04-22 03:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200422_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='last_word_rhyme',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='syllables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verse',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
